### ISSUE TITLE
./manage.py fixtree raises NotImplementedError

### ISSUE THREAD

**Issue by jrief** [fsbraun/djangocms4-utilities#1]
When I run `./manage.py fixtree` a

`NotImplementedError("remove_published_where has been replaced by ContentObj.admin_manager")`

is raised. Apparently djangocms-versioning changed their API somehow.

**Comment by fsbraun** [comment]
Will fix this today!

**Comment by fsbraun** [comment]
@jrief I have added a fix that should run on all versions of versioning. I couldn't test it, though. Can you give it a try?

**Comment by fsbraun** [comment]
Quick background: Versioning below 2.0 had a routine that patched the SQL statement of a queryset to remove `WHERE` conditions that restricted the version status. These `WHERE` statements are introduced by the `objects` manager to ensure only public versions are returned. As of versioning 2.0, the `admin_manager` allows accessing all objects and needs no patching of querysets.
